[package]
name = "fri"
version = "0.1.0"
edition = "2021"

[dependencies]
lambdaworks-crypto = { git = "https://github.com/lambdaclass/lambdaworks", rev = "a17b951" }
lambdaworks-math = { git = "https://github.com/lambdaclass/lambdaworks", rev = "a17b951" }
